default: &default
  avg:
    - learning_rate
    - action_entropy_parameter
    - data_efficiency
    - policy_different
    - receive_data_time
    - training_time
    - total_training_time
    - sgd_time
    - slice_time
  max:
    - sgd_time
    - wait_data_server_count
  min:
    - sgd_time
  total:
    - training_steps
  per_min:
    - sgd_round
    - receive_instance_total
    - receive_instance_rank_0
    - receive_instance_rank_1
    - receive_instance_rank_2
    - receive_instance_rank_3
    - receive_instance_rank_4
    - receive_instance_rank_5
    - receive_instance_rank_6
    - receive_instance_rank_7
    - receive_instance_rank_8
    - receive_instance_rank_9
    - receive_instance_rank_10
    - receive_instance_rank_11
    - receive_instance_rank_12
    - receive_instance_rank_13
    - receive_instance_rank_14
    - receive_instance_rank_15
    - receive_instance_rank_16
    - receive_instance_rank_17
    - receive_instance_rank_18
    - receive_instance_rank_19
    - receive_instance_rank_20
    - receive_instance_rank_21
    - receive_instance_rank_22
    - receive_instance_rank_23

development:
  <<: *default


production:
  <<: *default
