default: &default
  rollout_worker:
    - host_name: localhost
      host_ip: 127.0.0.1

development:
  <<: *default
  rollout_worker:
    - host_name: localhost
      host_ip: 0.0.0.0
  gpu_server:
    - host_name: localhost
      host_ip: 0.0.0.0
      gpu_num: 1

production:
  <<: *default

  rollout_worker:
#    - host_name: jssz-ai-newton-cpu-01
#      host_ip: 10.70.218.18
#    - host_name: jssz-ai-newton-cpu-02
#      host_ip: 10.70.218.17
#    - host_name: jssz-ai-newton-cpu-03
#      host_ip: 10.70.218.16
#    - host_name: jssz-ai-newton-cpu-04
#      host_ip: &cpu-04 10.70.218.15
#    - host_name: jssz-ai-newton-cpu-05
#      host_ip: &cpu-05 10.70.218.14
#    - host_name: jssz-ai-newton-cpu-06
#      host_ip: &cpu-06 10.70.218.13
#    - host_name: jssz-ai-newton-cpu-07
#      host_ip: &cpu-07 10.70.218.12
#    - host_name: jssz-ai-newton-cpu-08
#      host_ip: &cpu-08 10.70.218.11
#    - host_name: jssz-ai-newton-cpu-09
#      host_ip: &cpu-09 10.70.217.34
#    - host_name: jssz-ai-newton-cpu-10
#      host_ip: &cpu-10 10.70.217.33
#    - host_name: jssz-ai-newton-cpu-11
#      host_ip: &cpu-11 10.70.217.32
#    - host_name: jssz-ai-newton-cpu-12
#      host_ip: &cpu-12 10.70.217.31
#    - host_name: jssz-ai-newton-cpu-13
#      host_ip: &cpu-13 10.70.217.30
#    - host_name: jssz-ai-newton-cpu-14
#      host_ip: &cpu-14 10.70.217.29
#    - host_name: jssz-ai-newton-cpu-15
#      host_ip: &cpu-15 10.70.217.28
#    - host_name: jssz-ai-newton-cpu-16
#      host_ip: &cpu-16 10.70.217.27
#    - host_name: jssz-ai-newton-cpu-17
#      host_ip: &cpu-17 10.70.217.26
#    - host_name: jssz-ai-newton-cpu-18
#      host_ip: &cpu-18 10.70.217.25
#    - host_name: jssz-ai-newton-cpu-19
#      host_ip: &cpu-19 10.70.217.24
#    - host_name: jssz-ai-newton-cpu-20
#      host_ip: &cpu-20 10.70.217.23
#    - host_name: jssz-ai-newton-cpu-21
#      host_ip: &cpu-21 10.70.217.22
#    - host_name: jssz-ai-newton-cpu-22
#      host_ip: &cpu-22 10.70.217.21
#    - host_name: jssz-ai-newton-cpu-23
#      host_ip: &cpu-23 10.70.217.20
#    - host_name: jssz-ai-newton-cpu-24
#      host_ip: &cpu-24 10.70.217.19
#    - host_name: jssz-ai-newton-cpu-25
#      host_ip: &cpu-25 10.70.217.18
#    - host_name: jssz-ai-newton-cpu-26
#      host_ip: &cpu-26 10.70.217.17
#    - host_name: jssz-ai-newton-cpu-27
#      host_ip: &cpu-27 10.70.217.16
#    - host_name: jssz-ai-newton-cpu-28
#      host_ip: &cpu-28 10.70.217.15
#    - host_name: jssz-ai-newton-cpu-29
#      host_ip: &cpu-29 10.70.217.14
#    - host_name: jssz-ai-newton-cpu-30
#      host_ip: &cpu-30 10.70.217.13
#    - host_name: jssz-ai-newton-cpu-31
#      host_ip: &cpu-31 10.70.217.12
#    - host_name: jssz-ai-newton-cpu-32
#      host_ip: &cpu-32 10.70.217.11
#    - host_name: jssz-ai-newton-cpu-33
#      host_ip: &cpu-33 10.70.216.34
#    - host_name: jssz-ai-newton-cpu-34
#      host_ip: &cpu-34 10.70.216.33
#    - host_name: jssz-ai-newton-cpu-35
#      host_ip: &cpu-35 10.70.216.32
#    - host_name: jssz-ai-newton-cpu-36
#      host_ip: &cpu-36 10.70.216.31
#    - host_name: jssz-ai-newton-cpu-37
#      host_ip: &cpu-37 10.70.216.30
#    - host_name: jssz-ai-newton-cpu-38
#      host_ip: &cpu-38 10.70.216.29
#    - host_name: jssz-ai-newton-cpu-39
#      host_ip: &cpu-39 10.70.216.28
#    - host_name: jssz-ai-newton-cpu-40
#      host_ip: &cpu-40 10.70.216.27
#    - host_name: jssz-ai-newton-cpu-41
#      host_ip: &cpu-41 10.70.216.26
#    - host_name: jssz-ai-newton-cpu-42
#      host_ip: &cpu-42 10.70.216.25
#    - host_name: jssz-ai-newton-cpu-43
#      host_ip: &cpu-43 10.70.216.24
#    - host_name: jssz-ai-newton-cpu-44
#      host_ip: &cpu-44 10.70.216.23
#    - host_name: jssz-ai-newton-cpu-45
#      host_ip: &cpu-45 10.70.216.22
#    - host_name: jssz-ai-newton-cpu-46
#      host_ip: &cpu-46 10.70.216.21
#    - host_name: jssz-ai-newton-cpu-47
#      host_ip: &cpu-47 10.70.216.20
#    - host_name: jssz-ai-newton-cpu-48
#      host_ip: &cpu-48 10.70.216.19
#    - host_name: jssz-ai-newton-cpu-49
#      host_ip: &cpu-49 10.70.216.18
#    - host_name: jssz-ai-newton-cpu-50
#      host_ip: &cpu-50 10.70.216.17
#    - host_name: jssz-ai-newton-cpu-51
#      host_ip: &cpu-51 10.70.216.16
#    - host_name: jssz-ai-newton-cpu-52
#      host_ip: &cpu-52 10.70.216.15
#    - host_name: jssz-ai-newton-cpu-53
#      host_ip: &cpu-53 10.70.216.14
#    - host_name: jssz-ai-newton-cpu-54
#      host_ip: &cpu-54 10.70.216.13
#    - host_name: jssz-ai-newton-cpu-55
#      host_ip: &cpu-55 10.70.216.12
#    - host_name: jssz-ai-newton-cpu-56
#      host_ip: &cpu-56 10.70.216.11
#    - host_name: jssz-ai-newton-cpu-57
#      host_ip: &cpu-57 10.70.215.34
#    - host_name: jssz-ai-newton-cpu-58
#      host_ip: &cpu-58 10.70.215.33
#    - host_name: jssz-ai-newton-cpu-59
#      host_ip: &cpu-59 10.70.215.32
#    - host_name: jssz-ai-newton-cpu-60
#      host_ip: &cpu-60 10.70.215.31
#    - host_name: jssz-ai-newton-cpu-61
#      host_ip: &cpu-61 10.70.215.30
#    - host_name: jssz-ai-newton-cpu-62
#      host_ip: &cpu-62 10.70.215.29
#    - host_name: jssz-ai-newton-cpu-63
#      host_ip: &cpu-63 10.70.215.28
#    - host_name: jssz-ai-newton-cpu-64
#      host_ip: &cpu-64 10.70.215.27
#    - host_name: jssz-ai-newton-cpu-65
#      host_ip: &cpu-65 10.70.215.26
#    - host_name: jssz-ai-newton-cpu-66
#      host_ip: &cpu-66 10.70.215.25
#    - host_name: jssz-ai-newton-cpu-67
#      host_ip: &cpu-67 10.70.215.24
#    - host_name: jssz-ai-newton-cpu-68
#      host_ip: &cpu-68 10.70.215.23
#    - host_name: jssz-ai-newton-cpu-69
#      host_ip: &cpu-69 10.70.215.22
#    - host_name: jssz-ai-newton-cpu-70
#      host_ip: &cpu-70 10.70.215.21
#    - host_name: jssz-ai-newton-cpu-71
#      host_ip: &cpu-71 10.70.215.20
#    - host_name: jssz-ai-newton-cpu-72
#      host_ip: &cpu-72 10.70.215.19
#    - host_name: jssz-ai-newton-cpu-73
#      host_ip: &cpu-73 10.70.215.18
#    - host_name: jssz-ai-newton-cpu-74
#      host_ip: &cpu-74 10.70.215.17
#    - host_name: jssz-ai-newton-cpu-75
#      host_ip: &cpu-75 10.70.215.16
#    - host_name: jssz-ai-newton-cpu-76
#      host_ip: &cpu-76 10.70.215.15
#    - host_name: jssz-ai-newton-cpu-77
#      host_ip: &cpu-77 10.70.215.14
#    - host_name: jssz-ai-newton-cpu-78
#      host_ip: &cpu-78 10.70.215.13
#    - host_name: jssz-ai-newton-cpu-79
#      host_ip: &cpu-79 10.70.215.12
#    - host_name: jssz-ai-newton-cpu-80
#      host_ip: &cpu-80 10.70.215.11
#    - host_name: jssz-ai-newton-cpu-81
#      host_ip: &cpu-81 10.70.218.27
#    - host_name: jssz-ai-newton-cpu-82
#      host_ip: &cpu-82 10.70.218.28
#    - host_name: jssz-ai-newton-cpu-83
#      host_ip: &cpu-83 10.70.218.29
#    - host_name: jssz-ai-newton-cpu-84
#      host_ip: &cpu-84 10.70.218.30
#    - host_name: jssz-ai-newton-cpu-85
#      host_ip: &cpu-85 10.70.218.31
#    - host_name: jssz-ai-newton-cpu-86
#      host_ip: &cpu-86 10.70.218.32
#    - host_name: jssz-ai-newton-cpu-87
#      host_ip: &cpu-87 10.70.218.33
#    - host_name: jssz-ai-newton-cpu-88
#      host_ip: &cpu-88 10.70.218.34
#    - host_name: jssz-ai-newton-cpu-89
#      host_ip: &cpu-89 10.70.219.11
#    - host_name: jssz-ai-newton-cpu-90
#      host_ip: &cpu-90 10.70.219.12
#    - host_name: jssz-ai-newton-cpu-91
#      host_ip: &cpu-91 10.70.219.13
#    - host_name: jssz-ai-newton-cpu-92
#      host_ip: &cpu-92 10.70.219.14
#    - host_name: jssz-ai-newton-cpu-93
#      host_ip: &cpu-93 10.70.218.19
#    - host_name: jssz-ai-newton-cpu-94
#      host_ip: &cpu-94 10.70.218.20
#    - host_name: jssz-ai-newton-cpu-95
#      host_ip: &cpu-95 10.70.218.21
#    - host_name: jssz-ai-newton-cpu-96
#      host_ip: &cpu-96 10.70.218.22
#    - host_name: jssz-ai-newton-cpu-97
#      host_ip: &cpu-97 10.70.218.23
#    - host_name: jssz-ai-newton-cpu-98
#      host_ip: &cpu-98 10.70.218.24
#    - host_name: jssz-ai-newton-cpu-99
#      host_ip: &cpu-99 10.70.218.25
#    - host_name: jssz-ai-newton-cpu-100
#      host_ip: &cpu-100 10.70.218.26
#    - host_name: jssz-ai-newton-cpu-161
#      host_ip: &cpu-161 10.71.149.22
#    - host_name: jssz-ai-newton-cpu-162
#      host_ip: &cpu-162 10.71.149.34
#    - host_name: jssz-ai-newton-cpu-163
#      host_ip: &cpu-163 10.71.149.43
#    - host_name: jssz-ai-newton-cpu-164
#      host_ip: &cpu-164 10.71.149.44
#    - host_name: jssz-ai-newton-cpu-165
#      host_ip: &cpu-165 10.71.149.45
#    - host_name: jssz-ai-newton-cpu-166
#      host_ip: &cpu-166 10.71.149.46
#    - host_name: jssz-ai-newton-cpu-167
#      host_ip: &cpu-167 10.71.150.19
#    - host_name: jssz-ai-newton-cpu-168
#      host_ip: &cpu-168 10.71.150.30
#    - host_name: jssz-ai-newton-cpu-169
#      host_ip: &cpu-169 10.71.150.31
#    - host_name: jssz-ai-newton-cpu-170
#      host_ip: &cpu-170 10.71.150.25
#    - host_name: jssz-ai-newton-cpu-171
#      host_ip: &cpu-171 10.71.150.26
#    - host_name: jssz-ai-newton-cpu-172
#      host_ip: &cpu-172 10.71.150.27
#    - host_name: jssz-ai-newton-cpu-173
#      host_ip: &cpu-173 10.71.150.28
#    - host_name: jssz-ai-newton-cpu-174
#      host_ip: &cpu-174 10.71.151.19
#    - host_name: jssz-ai-newton-cpu-175
#      host_ip: &cpu-175 10.71.151.30
#    - host_name: jssz-ai-newton-cpu-176
#      host_ip: &cpu-176 10.71.151.31
#    - host_name: jssz-ai-newton-cpu-177
#      host_ip: &cpu-177 10.71.152.19
#    - host_name: jssz-ai-newton-cpu-178
#      host_ip: &cpu-178 10.71.152.29
#    - host_name: jssz-ai-newton-cpu-179
#      host_ip: &cpu-179 10.71.152.30
#    - host_name: jssz-ai-newton-cpu-180
#      host_ip: &cpu-180 10.71.152.31
#    - host_name: jssz-ai-newton-cpu-181
#      host_ip: &cpu-181 10.71.153.18
#    - host_name: jssz-ai-newton-cpu-182
#      host_ip: &cpu-182 10.71.153.19
#    - host_name: jssz-ai-newton-cpu-183
#      host_ip: &cpu-183 10.71.153.29
#    - host_name: jssz-ai-newton-cpu-184
#      host_ip: &cpu-184 10.71.153.30
#    - host_name: jssz-ai-newton-cpu-185
#      host_ip: &cpu-185 10.71.153.31
#    - host_name: jssz-ai-newton-cpu-186
#      host_ip: &cpu-186 10.71.154.18
#    - host_name: jssz-ai-newton-cpu-187
#      host_ip: &cpu-187 10.71.154.19
#    - host_name: jssz-ai-newton-cpu-188
#      host_ip: &cpu-188 10.71.154.29
#    - host_name: jssz-ai-newton-cpu-189
#      host_ip: &cpu-189 10.71.154.30
#    - host_name: jssz-ai-newton-cpu-190
#      host_ip: &cpu-190 10.71.154.31
#    - host_name: jssz-ai-newton-cpu-191
#      host_ip: &cpu-191 10.71.155.18
#    - host_name: jssz-ai-newton-cpu-192
#      host_ip: &cpu-192 10.71.155.19
#    - host_name: jssz-ai-newton-cpu-193
#      host_ip: &cpu-193 10.71.155.29
#    - host_name: jssz-ai-newton-cpu-194
#      host_ip: &cpu-194 10.71.155.30
#    - host_name: jssz-ai-newton-cpu-195
#      host_ip: &cpu-195 10.71.155.31
#    - host_name: jssz-ai-newton-cpu-196
#      host_ip: &cpu-196 10.71.155.41
#    - host_name: jssz-ai-newton-cpu-197
#      host_ip: &cpu-197 10.71.155.42
#    - host_name: jssz-ai-newton-cpu-198
#      host_ip: &cpu-198 10.71.155.43
#    - host_name: jssz-ai-newton-cpu-199
#      host_ip: &cpu-199 10.71.156.17
#    - host_name: jssz-ai-newton-cpu-200
#      host_ip: &cpu-200 10.71.156.18
#    - host_name: jssz-ai-newton-cpu-201
#      host_ip: &cpu-201 10.71.156.19
#    - host_name: jssz-ai-newton-cpu-202
#      host_ip: &cpu-202 10.71.156.29
#    - host_name: jssz-ai-newton-cpu-203
#      host_ip: &cpu-203 10.71.156.30
#    - host_name: jssz-ai-newton-cpu-204
#      host_ip: &cpu-204 10.71.156.31
#    - host_name: jssz-ai-newton-cpu-205
#      host_ip: &cpu-205 10.71.157.17
#    - host_name: jssz-ai-newton-cpu-206
#      host_ip: &cpu-206 10.71.157.18
#    - host_name: jssz-ai-newton-cpu-207
#      host_ip: &cpu-207 10.71.157.19
#    - host_name: jssz-ai-newton-cpu-208
#      host_ip: &cpu-208 10.71.157.29
#    - host_name: jssz-ai-newton-cpu-209
#      host_ip: &cpu-209 10.71.157.30
#    - host_name: jssz-ai-newton-cpu-210
#      host_ip: &cpu-210 10.71.157.31
#    - host_name: jssz-ai-newton-cpu-211
#      host_ip: &cpu-211 10.71.158.17
#    - host_name: jssz-ai-newton-cpu-212
#      host_ip: &cpu-212 10.71.158.18
#    - host_name: jssz-ai-newton-cpu-213
#      host_ip: &cpu-213 10.71.158.19
#    - host_name: jssz-ai-newton-cpu-214
#      host_ip: &cpu-214 10.71.158.29
#    - host_name: jssz-ai-newton-cpu-215
#      host_ip: &cpu-215 10.71.158.30
#    - host_name: jssz-ai-newton-cpu-216
#      host_ip: &cpu-216 10.71.158.31
#    - host_name: jssz-ai-newton-cpu-217
#      host_ip: &cpu-217 10.71.159.17
#    - host_name: jssz-ai-newton-cpu-218
#      host_ip: &cpu-218 10.71.159.18
#    - host_name: jssz-ai-newton-cpu-219
#      host_ip: &cpu-219 10.71.159.19
#    - host_name: jssz-ai-newton-cpu-220
#      host_ip: &cpu-220 10.71.159.29

  gpu_server:
#    - host_name: jssz-ai-newton-cpu-28
#      host_ip: &cpu-28 10.70.217.15
#    - host_name: jssz-ai-newton-cpu-29
#      host_ip: &cpu-29 10.70.217.14
#    - host_name: jssz-ai-newton-cpu-30
#      host_ip: &cpu-30 10.70.217.13
#    - host_name: jssz-ai-newton-cpu-57
#      host_ip: &cpu-57 10.70.215.34
#    - host_name: jssz-ai-newton-cpu-58
#      host_ip: &cpu-58 10.70.215.33
#    - host_name: jssz-ai-newton-cpu-59
#      host_ip: &cpu-59 10.70.215.32
#    - host_name: jssz-ai-newton-cpu-60
#      host_ip: &cpu-60 10.70.215.31
#    - host_name: jssz-ai-newton-gpu-01
#      host_ip: &gpu-01 10.70.234.21
#      gpu_num: 8
#    - host_name: jssz-ai-newton-gpu-02
#      host_ip: &gpu-02 10.70.238.34
#      gpu_num: 8
#    - host_name: jssz-ai-newton-gpu-03
#      host_ip: &gpu-03 10.70.234.33
#      gpu_num: 8
#    - host_name: jssz-ai-newton-gpu-04
#      host_ip: &gpu-04 10.70.235.21
#      gpu_num: 8
#    - host_name: jssz-ai-newton-gpu-05
#      host_ip: &gpu-05 10.70.235.33
#      gpu_num: 8
#    - host_name: jssz-ai-newton-gpu-06
#      host_ip: &gpu-06 10.70.236.21
#      gpu_num: 8
#    - host_name: jssz-ai-newton-gpu-07
#      host_ip: &gpu-07 10.70.236.34
#      gpu_num: 8
#    - host_name: jssz-ai-newton-gpu-08
#      host_ip: &gpu-08 10.70.237.22
#      gpu_num: 8
#    - host_name: jssz-ai-newton-gpu-09
#      host_ip: &gpu-09 10.70.237.34
#      gpu_num: 8
#    - host_name: jssz-ai-newton-gpu-10
#      host_ip: &gpu-10 10.70.238.22
#      gpu_num: 8

  name_server:
#    host: *gpu-01

  training_server:
    host:
#      - *gpu-01
#      - *gpu-02
#      - *gpu-03
#      - *gpu-04
#      - *gpu-05
#      - *gpu-06
#      - *gpu-07
#      - *gpu-08
#      - *gpu-09
#      - *gpu-10

  inference_server:
#    - ip: *cpu-27
#      gpu: 0
#      cpu: 16
#    - ip: *cpu-28
#      gpu: 0
#      cpu: 16
#    - ip: *cpu-29
#      gpu: 0
#      cpu: 16
#    - ip: *cpu-30
#      gpu: 0
#      cpu: 16
#    - ip: *cpu-57
#      gpu: 0
#      cpu: 16
#    - ip: *cpu-58
#      gpu: 0
#      cpu: 16
#    - ip: *cpu-59
#      gpu: 0
#      cpu: 16
#    - ip: *cpu-60
#      gpu: 0
#      cpu: 16

  log_server:
#    host: *gpu-01

#  evaluation_server: *gpu-01
